name: "QodanaConfiguration"
baseProfile: empty

inspections:
  - group: Typos
    enabled: false
    inspections:
      - id: SpellCheckingInspection
        enabled: false

  - id: XmlHighlightingInspection
    enabled: false

  - id: JavaTestCoverageInspection
    enabled: true
    severity: ERROR
    scope: Production
    options:
      minimumLineCoverage: 86

  - id: JvmCoverageInspection
    enabled: true
    severity: WARNING
    options:
      classThreshold: 86
      methodThreshold: 86
      warnMissingCoverage: true

  - id: JavaCyclomaticComplexity
    enabled: true
    severity: ERROR
    options:
      m_limit: 10
      c_limit: 80
      p_limit: 400

  - id: JavaNPathComplexityInspection
    enabled: true
    severity: ERROR
    options:
      NPathLimit: 200

  - id: JavaMethodMetrics
    enabled: true
    severity: ERROR
    options:
      methodLimit: 50
      parameterLimit: 5
      throwsStatementsLimit: 2

  - id: JavaClassMetrics
    enabled: true
    severity: ERROR
    options:
      classLimit: 800
      methodCountLimit: 30
      fieldCountLimit: 20

  - id: JavaOverlyNestedBlock
    enabled: true
    severity: ERROR
    options:
      limit: 4

  - id: JavaOverlyComplexBooleanExpression
    enabled: true
    severity: ERROR
    options:
      limit: 4