name: "QodanaConfiguration"
baseProfile: qodana.recommended

inspections:
  - group: "XML"
    enabled: false

  - group: "Dependency analysis"
    enabled: false

  - group: "Java"
    enabled: true

  - group: "General"
    enabled: true

  - group: "Spring"
    enabled: true

  - group: "Code Coverage"
    enabled: true

  - inspection: GrazieInspection
    enabled: false

  - inspection: XmlHighlightingInspection
    enabled: false

  - inspection: JavaTestCoverageInspection
    enabled: true
    severity: ERROR
    options:
      minimumLineCoverage: 86

  - inspection: JvmCoverageInspection
    enabled: true
    severity: WARNING
    options:
      classThreshold: 86
      methodThreshold: 86
      warnMissingCoverage: true

  - inspection: JavaCyclomaticComplexity
    enabled: true
    severity: ERROR
    options:
      m_limit: 10
      c_limit: 80
      p_limit: 400

  - inspection: JavaNPathComplexityInspection
    enabled: true
    severity: ERROR
    options:
      NPathLimit: 200

  - inspection: JavaMethodMetrics
    enabled: true
    severity: ERROR
    options:
      methodLimit: 50
      parameterLimit: 5
      throwsStatementsLimit: 2

  - inspection: JavaClassMetrics
    enabled: true
    severity: ERROR
    options:
      classLimit: 800
      methodCountLimit: 30
      fieldCountLimit: 20

  - inspection: JavaOverlyNestedBlock
    enabled: true
    severity: ERROR
    options:
      limit: 4

  - inspection: JavaOverlyComplexBooleanExpression
    enabled: true
    severity: ERROR
    options:
      limit: 4

  - inspection: OverlyComplexAnonymousInnerClass
    enabled: true
    severity: INFORMATION
    options:
      limit: 0

  - inspection: OverlyNestedMethod
    enabled: true
    severity: INFORMATION
    options:
      limit: 0


  - inspection: CyclomaticComplexityInspection
    enabled: true
    severity: INFORMATION
    options:
      limit: 0

  - inspection: OverlyComplexMethod
    enabled: true
    severity: INFORMATION
    options:
      limit: 0

  - inspection: OverlyComplexClass
    enabled: true
    severity: INFORMATION
    options:
      limit: 0
