# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle (Java 21)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle wrapper executable (Linux)
        run: chmod +x ./gradlew

      - name: Setup Gradle (caching + env)
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Test
        run: ./gradlew --no-daemon clean build check

      - name: Mutation Testing (PIT)
        # Optional: nur auf Push laufen lassen, um PRs zu beschleunigen:
        # if: github.event_name == 'push'
        run: ./gradlew --no-daemon pitest

      - name: Collect test reports (JUnit/Spock)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          if-no-files-found: ignore
          retention-days: 7
          path: |
            build/test-results/test/**/*.xml
            build/reports/tests/test/**
            build/reports/spock/**

      - name: Collect Jacoco coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          if-no-files-found: ignore
          retention-days: 7
          path: |
            build/reports/jacoco/test/jacocoTestReport.xml
            build/reports/jacoco/test/html/**

      - name: Collect PIT reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          if-no-files-found: ignore
          retention-days: 7
          path: |
            build/reports/pitest/**
            build/reports/pit-reports/**

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
